### PR TITLE
Add basic CSS

### PR DESCRIPTION
**Pull request by nithinbekal**

### CODE REVIEW

**Comment by kbrock** [comment]
Nice. The `autofocus: true` is a nice touch.

**Comment by nithinbekal** [comment]
@kbrock I started added some CSS so we have some sort of a UI to begin with. I'm not very good with UI, so would love to hear if you have feedback.

screen shot 2015-09-21 at 10 44 07 pm

**Comment by kbrock** [comment]
I think it looks great

**Comment by kbrock** [comment]
There is another action cable chat project on github. Went back looking for it but can't find it. Think the dev was attempting to make it past the 3 commits that most people have in their "actioncable-chat-test" repo.

Not sure where to go from here. There are so many things to add, but don't want to obscure this project. Should we create a different project for something more?

**Comment by nithinbekal** [comment]
Ok, I'm merging this in. With this in place, we should be able to start adding more advanced demos. We can make improvements to the design directly in the branch for each example.

**Comment by nithinbekal** [comment]
@kbrock There's this official [ActionCable examples repo](https://github.com/rails/actioncable-examples) and this [reactjs with ActionCable example](https://github.com/vipulnsward/actioncable-examples/tree/es6) that I've come across.

Maybe it would be more useful if the README linked to other example projects rather than having everything in the same repo.

I still want to improve some of the things about this repo, like using websockets to send the messages to the server instead of using an ajax form. For the other stuff, having separate repositories would be great.

**Comment by kbrock** [comment]
Im not able to find it but there was another repo with a non-trivial chat. Oh well.

I like the Ajax to the server in the "basic branch" because it feels like the suggested rails path.

On other branches, I agree. Websockets everywhere. Especially if we are using react or some other chat technology

**Pull request merged**
